# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving:1.0.0
    ports:
      - "6758:6758"
    volumes:
      - ./models:/code/models
    environment:
      - FLASK_LOG = ${FLASK_LOG}
      - MODELS_DIR = ${MODELS_DIR}
      - COMET_WORKSPACE = ${COMET_WORKSPACE}
      - COMET_API_KEY = ${COMET_API_KEY}
      - DEFAULT_MODEL = ${DEFAULT_MODEL}
      - DEFAULT_VERSION = ${DEFAULT_VERSION}
      - DEFAULT_FILENAME = ${DEFAULT_FILENAME}
  jupyter:
    build:
      context: ./
      dockerfile: ./Dockerfile.jupyter
    image: ift6758/jupyter:1.0.0
    ports:
      - 9999:9999
    volumes:
      - ./ift6758/ift6758/notebooks:/code/notebooks
